-- Migration: create headcount_logs table and storage bucket policy
-- Apply this in Supabase SQL editor

-- Table
create table if not exists headcount_logs (
  id             bigint generated by default as identity primary key,
  episode_id     bigint references alert_episodes(id) on delete cascade,
  ts             double precision not null,
  high_count     integer not null default 0,
  mid_count      integer not null default 0,
  low_count      integer not null default 0,
  total_count    integer not null default 0,
  image_url      text,
  trigger_source text not null default 'auto'
);

create index if not exists idx_headcount_logs_episode_id
  on headcount_logs (episode_id);

create index if not exists idx_headcount_logs_ts
  on headcount_logs (ts);

-- Enable RLS
alter table headcount_logs enable row level security;

-- anon read/write (matches existing alert_episodes setup)
create policy "anon_read_headcount_logs"
  on headcount_logs for select
  using (auth.role() = 'anon');

create policy "anon_write_headcount_logs"
  on headcount_logs for insert
  with check (auth.role() = 'anon');

create policy "anon_update_headcount_logs"
  on headcount_logs for update
  using (auth.role() = 'anon');

-- Storage bucket: headcount-captures
-- Run this separately in Supabase SQL editor after creating the bucket manually
-- in Storage > New bucket > name: headcount-captures > public: true
insert into storage.buckets (id, name, public)
  values ('headcount-captures', 'headcount-captures', true)
  on conflict (id) do nothing;

create policy "anon_upload_headcount_captures"
  on storage.objects for insert
  with check (bucket_id = 'headcount-captures' and auth.role() = 'anon');

create policy "anon_read_headcount_captures"
  on storage.objects for select
  using (bucket_id = 'headcount-captures');
