-- Tables
create table if not exists alert_episodes (
  id bigint generated by default as identity primary key,
  started_ts double precision not null,
  last_updated_ts double precision not null,
  current_state text not null,
  status text not null default 'active',
  meta jsonb
);

create index if not exists idx_alert_episodes_started_ts
  on alert_episodes (started_ts);

create table if not exists alert_transitions (
  id bigint generated by default as identity primary key,
  episode_id bigint not null references alert_episodes(id) on delete cascade,
  ts double precision not null,
  state text not null,
  meta jsonb
);

create index if not exists idx_alert_transitions_episode_id
  on alert_transitions (episode_id);

create index if not exists idx_alert_transitions_ts
  on alert_transitions (ts);

-- Enable RLS
alter table alert_episodes enable row level security;
alter table alert_transitions enable row level security;

-- OPTION A: anon read/write (matches existing anon sensor_readings setup)
create policy "anon_read_alert_episodes"
  on alert_episodes for select
  using (auth.role() = 'anon');

create policy "anon_write_alert_episodes"
  on alert_episodes for insert
  with check (auth.role() = 'anon');

create policy "anon_update_alert_episodes"
  on alert_episodes for update
  using (auth.role() = 'anon');

create policy "anon_read_alert_transitions"
  on alert_transitions for select
  using (auth.role() = 'anon');

create policy "anon_write_alert_transitions"
  on alert_transitions for insert
  with check (auth.role() = 'anon');